name: bike              # Bike sharing pattern identifier
channels:
  - defaults
dependencies:
  - python=3.8.12
  - dash=1.19.0
  - jupyterlab=3.2.9
  - numpy=1.21.2
  - pandas=1.4.1
  - pip=21.2.4
  - plotly=5.1.0
  - tabulate=0.8.9      # Required by pandas.Dataframe.to_markdown()
  - pip:
    - nbclassic>=0.2.8  # Required to avoid some bugs with latest jupyterlab.
                        # Ref: https://stackoverflow.com/questions/68121775/jupyterlab-is-broken

